name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
  schedule:
    - cron: '00 04 * * 1' # 4am every Monday
  workflow_dispatch:
jobs:
  test_repo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.12
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up conda with Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install OpenFF Toolkit and OpenMM
      run: conda install -c conda-forge pip 'openff-toolkit-base>=0.18.0' rustworkx rdkit openmm pyxdg gemmi
    - name: Install PyTorch and graph libraries
      run: pip install torch torch_geometric igraph pytest
    - name: Install Pablo
      run: pip install git+https://github.com/openforcefield/openff-pablo.git@v0.2.0
    - name: Test install
      run: pip install -e .
    - name: Test import
      run: python -c "from garnetff import garnet"
    - name: Run tests
      run: time pytest
  test_pypi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.12
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up conda with Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install OpenFF Toolkit and OpenMM
      run: conda install -c conda-forge pip 'openff-toolkit-base>=0.18.0' rustworkx rdkit openmm pyxdg gemmi
    - name: Install PyTorch and graph libraries
      run: pip install torch torch_geometric igraph pytest
    - name: Install Pablo
      run: pip install git+https://github.com/openforcefield/openff-pablo.git@v0.2.0
    - name: Test install
      run: pip install garnetff
    - name: Test import
      run: python -c "from garnetff import garnet"
    - name: Run tests
      run: time pytest
